### PR TITLE
Test uniforms have same data as struct members of same type

### PR DESCRIPTION
**Pull request by greggman**
Does this test make sense?

### CODE REVIEW

**Comment by brendan-duncan** [comment]
Seems like a good test

**Comment by brendan-duncan** [comment]
I hadn't had a chance to test it yet, been busy finishing work before the holiday. I should really document this stuff, especially the AST. Without proper c++ classes, the dynamic JS objects aren't very self documenting. I'll make it my next project.

**Comment by brendan-duncan** [comment]
I fixed up the test and the reflected info. I still need to work on documentation, and making sure returned info is consistent. Maybe I'll switch to classes instead of generic JS objects, that would help make sure the API is more consistent. If only there was more time.

The one test case you had that didn't make much sense is testing the offset. You had `test.equals(uniInfo.offset, member.offset);`, but the uniform buffer itself doesn't have an offset.

**Comment by greggman** [comment]
thanks brendan!

**Comment by brendan-duncan** [comment]
I started cleaning up my messy Javascript and refactored WgslParser to use AST classes defined in wgsl_ast.js. This will make things more consistent and easier to figure out.

Next, I'll do a pass at the information classes generated by WgslReflect to make sure that's more consistent and easier to figure out...as soon as I can get to doing that.

**Pull request merged**
